const GAME_WORLDS = [
  { id: "calc", world: "算式山丘", shortLabel: "算", practice: "兩步驟應用問題", color: "#ffd66b" },
  { id: "measure", world: "彩虹尺橋", shortLabel: "量", practice: "公尺和公分", color: "#8bd3ff" },
  { id: "shape", world: "積木分類森林", shortLabel: "分", practice: "分類與立體形體", color: "#9ee6a6" },
  { id: "share", world: "公平野餐桌", shortLabel: "配", practice: "平均分配與分裝", color: "#ffbd91" },
  { id: "fraction", world: "分數蛋糕湖", shortLabel: "半", practice: "平分、幾分之一、簡單分數比較", color: "#d7c4ff" },
  { id: "final", world: "期末星光城", shortLabel: "勇", practice: "綜合挑戰", color: "#ffe68a" }
];

const MATH_QUESTIONS = [
  {
    id: "calc-001",
    world: "算式山丘",
    shortLabel: "算",
    skill: "先乘再加",
    type: "single-choice",
    question: "一包星星貼紙有 5 張，小宇買了 3 包，又得到 4 張。他一共有幾張貼紙？",
    choices: ["15張", "19張", "20張", "23張"],
    answer: "19張",
    explanation: "先算 5×3＝15，再算 15＋4＝19。",
    difficulty: 1
  },
  {
    id: "calc-002",
    world: "算式山丘",
    shortLabel: "算",
    skill: "先乘再減",
    type: "single-choice",
    question: "每盒有 6 顆彩色石頭，安安有 4 盒，送給朋友 5 顆，還剩幾顆？",
    choices: ["19顆", "21顆", "24顆", "29顆"],
    answer: "19顆",
    explanation: "先算 6×4＝24，再算 24－5＝19。",
    difficulty: 1
  },
  {
    id: "calc-003",
    world: "算式山丘",
    shortLabel: "算",
    skill: "先加再分組",
    type: "formula-choice",
    question: "桌上有 12 顆葡萄，媽媽又放上 8 顆，平均分給 4 人。哪一個算式正確？",
    choices: ["12＋8÷4", "(12＋8)÷4", "12×8÷4", "12＋4÷8"],
    answer: "(12＋8)÷4",
    explanation: "要先把葡萄合起來，所以先算 12＋8，再平均分給 4 人。",
    difficulty: 2
  },
  {
    id: "calc-004",
    world: "算式山丘",
    shortLabel: "算",
    skill: "先減再乘",
    type: "single-choice",
    question: "一排有 9 個花盆，其中 2 個空盆要拿走。剩下的花盆每盆種 3 朵花，一共種幾朵？",
    choices: ["18朵", "21朵", "27朵", "33朵"],
    answer: "21朵",
    explanation: "先算剩下 9－2＝7 盆，再算 7×3＝21 朵。",
    difficulty: 2
  },
  {
    id: "calc-005",
    world: "算式山丘",
    shortLabel: "算",
    skill: "兩步驟比較",
    type: "single-choice",
    question: "小晴有 28 元，買一枝 9 元的鉛筆和一本 12 元的小本子，還剩幾元？",
    choices: ["5元", "7元", "9元", "21元"],
    answer: "7元",
    explanation: "先算花了 9＋12＝21 元，再算 28－21＝7 元。",
    difficulty: 1
  },
  {
    id: "calc-006",
    world: "算式山丘",
    shortLabel: "算",
    skill: "看圖選算式",
    type: "picture-choice",
    visual: "🍓🍓🍓 | 🍓🍓🍓 | 🍓🍓🍓  再加 🍓🍓",
    question: "圖中有 3 盤草莓，每盤 3 顆，又多 2 顆。哪一個算式可以算出總數？",
    choices: ["3＋3＋2", "3×3＋2", "3×2＋3", "3×3－2"],
    answer: "3×3＋2",
    explanation: "3 盤、每盤 3 顆是 3×3，再加 2 顆。",
    difficulty: 1
  },
  {
    id: "calc-007",
    world: "算式山丘",
    shortLabel: "算",
    skill: "是非判斷",
    type: "true-false",
    question: "「4 個袋子，每袋 5 顆糖，再吃掉 3 顆」可以用 4×5－3 來算。",
    choices: ["是", "不是"],
    answer: "是",
    explanation: "先算一共有 4×5 顆，再減掉吃掉的 3 顆。",
    difficulty: 1
  },
  {
    id: "calc-008",
    world: "算式山丘",
    shortLabel: "算",
    skill: "括號意義",
    type: "single-choice",
    question: "小隊先收集 16 片葉子，又收集 8 片，平均貼在 6 張卡片上，每張貼幾片？",
    choices: ["3片", "4片", "6片", "24片"],
    answer: "4片",
    explanation: "先合起來 16＋8＝24，再平均分成 6 份，24÷6＝4。",
    difficulty: 2
  },
  {
    id: "calc-009",
    world: "算式山丘",
    shortLabel: "算",
    skill: "先除再加",
    type: "single-choice",
    question: "18 顆小球平均放進 3 個盒子，每盒放完後，老師又在每盒加 2 顆。每盒現在有幾顆？",
    choices: ["6顆", "8顆", "12顆", "20顆"],
    answer: "8顆",
    explanation: "先算 18÷3＝6，再算每盒 6＋2＝8。",
    difficulty: 2
  },
  {
    id: "calc-010",
    world: "算式山丘",
    shortLabel: "算",
    skill: "選正確答案",
    type: "single-choice",
    question: "每張桌子坐 4 人，5 張桌子都坐滿，後來有 3 人先離開，現在還有幾人？",
    choices: ["17人", "20人", "23人", "12人"],
    answer: "17人",
    explanation: "先算 4×5＝20 人，再算 20－3＝17 人。",
    difficulty: 1
  },

  {
    id: "measure-001",
    world: "彩虹尺橋",
    shortLabel: "量",
    skill: "公尺和公分",
    type: "single-choice",
    question: "1 公尺等於幾公分？",
    choices: ["10公分", "50公分", "100公分", "1000公分"],
    answer: "100公分",
    explanation: "1 公尺＝100 公分。",
    difficulty: 1
  },
  {
    id: "measure-002",
    world: "彩虹尺橋",
    shortLabel: "量",
    skill: "長度換算",
    type: "single-choice",
    question: "2 公尺 30 公分，也可以說是幾公分？",
    choices: ["23公分", "130公分", "203公分", "230公分"],
    answer: "230公分",
    explanation: "2 公尺是 200 公分，200＋30＝230 公分。",
    difficulty: 1
  },
  {
    id: "measure-003",
    world: "彩虹尺橋",
    shortLabel: "量",
    skill: "長度比較",
    type: "single-choice",
    question: "哪一個比較長？",
    choices: ["80公分", "1公尺", "70公分", "90公分"],
    answer: "1公尺",
    explanation: "1 公尺＝100 公分，比 80、70、90 公分都長。",
    difficulty: 1
  },
  {
    id: "measure-004",
    world: "彩虹尺橋",
    shortLabel: "量",
    skill: "加法量感",
    type: "single-choice",
    question: "一條彩帶長 1 公尺 20 公分，又接上一條 30 公分的彩帶，一共長幾公分？",
    choices: ["50公分", "120公分", "150公分", "230公分"],
    answer: "150公分",
    explanation: "1 公尺 20 公分是 120 公分，120＋30＝150 公分。",
    difficulty: 2
  },
  {
    id: "measure-005",
    world: "彩虹尺橋",
    shortLabel: "量",
    skill: "減法量感",
    type: "single-choice",
    question: "繩子長 2 公尺，用掉 45 公分，還剩幾公分？",
    choices: ["55公分", "145公分", "155公分", "245公分"],
    answer: "155公分",
    explanation: "2 公尺是 200 公分，200－45＝155 公分。",
    difficulty: 2
  },
  {
    id: "measure-006",
    world: "彩虹尺橋",
    shortLabel: "量",
    skill: "是非判斷",
    type: "true-false",
    question: "小桌子的高度大約是 60 公尺。",
    choices: ["是", "不是"],
    answer: "不是",
    explanation: "60 公尺非常高，小桌子大約用公分來說，比較可能是 60 公分。",
    difficulty: 1
  },
  {
    id: "measure-007",
    world: "彩虹尺橋",
    shortLabel: "量",
    skill: "選合適單位",
    type: "single-choice",
    question: "量教室門的高度，最適合用哪一個單位？",
    choices: ["公尺", "公分", "公斤", "分鐘"],
    answer: "公尺",
    explanation: "門比較高，常用公尺來表示高度。",
    difficulty: 1
  },
  {
    id: "measure-008",
    world: "彩虹尺橋",
    shortLabel: "量",
    skill: "看圖判斷",
    type: "picture-choice",
    visual: "鉛筆：15公分　尺：30公分　書桌：1公尺",
    question: "圖中的書桌比尺長多少公分？",
    choices: ["30公分", "70公分", "85公分", "130公分"],
    answer: "70公分",
    explanation: "1 公尺＝100 公分，100－30＝70 公分。",
    difficulty: 2
  },
  {
    id: "measure-009",
    world: "彩虹尺橋",
    shortLabel: "量",
    skill: "排列長短",
    type: "single-choice",
    question: "哪一組是由短到長排列？",
    choices: ["120公分、90公分、1公尺", "80公分、1公尺、130公分", "1公尺、70公分、150公分", "140公分、1公尺、60公分"],
    answer: "80公分、1公尺、130公分",
    explanation: "1 公尺是 100 公分，所以 80、100、130 是由短到長。",
    difficulty: 2
  },
  {
    id: "measure-010",
    world: "彩虹尺橋",
    shortLabel: "量",
    skill: "長度差",
    type: "single-choice",
    question: "小路長 3 公尺，彩虹橋長 250 公分。小路比彩虹橋長幾公分？",
    choices: ["50公分", "53公分", "250公分", "550公分"],
    answer: "50公分",
    explanation: "3 公尺＝300 公分，300－250＝50 公分。",
    difficulty: 2
  },

  {
    id: "shape-001",
    world: "積木分類森林",
    shortLabel: "分",
    skill: "立體形體",
    type: "single-choice",
    question: "像球一樣可以向很多方向滾動的立體形體是什麼？",
    choices: ["球", "正方體", "長方體", "圓柱"],
    answer: "球",
    explanation: "球的表面彎彎的，可以向很多方向滾動。",
    difficulty: 1
  },
  {
    id: "shape-002",
    world: "積木分類森林",
    shortLabel: "分",
    skill: "立體形體",
    type: "single-choice",
    question: "像罐子一樣，上下有圓形面的立體形體是什麼？",
    choices: ["球", "圓柱", "正方體", "三角形"],
    answer: "圓柱",
    explanation: "圓柱的上下兩面是圓形，側面是彎曲的。",
    difficulty: 1
  },
  {
    id: "shape-003",
    world: "積木分類森林",
    shortLabel: "分",
    skill: "分類依據",
    type: "single-choice",
    question: "把積木分成「能滾」和「不能滾」兩堆，是依照什麼分類？",
    choices: ["顏色", "大小", "能不能滾動", "名字長短"],
    answer: "能不能滾動",
    explanation: "題目說分成能滾和不能滾，所以分類依據是能不能滾動。",
    difficulty: 1
  },
  {
    id: "shape-004",
    world: "積木分類森林",
    shortLabel: "分",
    skill: "看圖分類",
    type: "picture-choice",
    visual: "🧊 🧊 🧱 🥫 ⚽",
    question: "圖中最適合放在「圓圓會滾」這一類的是哪一個？",
    choices: ["正方體", "長方體", "圓柱", "球和圓柱"],
    answer: "球和圓柱",
    explanation: "球會滾，圓柱也能沿著彎曲的側面滾動。",
    difficulty: 2
  },
  {
    id: "shape-005",
    world: "積木分類森林",
    shortLabel: "分",
    skill: "是非判斷",
    type: "true-false",
    question: "正方體的每一個面看起來都是正方形。",
    choices: ["是", "不是"],
    answer: "是",
    explanation: "正方體有 6 個面，每個面都是正方形。",
    difficulty: 1
  },
  {
    id: "shape-006",
    world: "積木分類森林",
    shortLabel: "分",
    skill: "立體形體",
    type: "single-choice",
    question: "鞋盒最像哪一種立體形體？",
    choices: ["球", "長方體", "圓柱", "圓形"],
    answer: "長方體",
    explanation: "鞋盒有長長方方的面，最像長方體。",
    difficulty: 1
  },
  {
    id: "shape-007",
    world: "積木分類森林",
    shortLabel: "分",
    skill: "分類統計",
    type: "single-choice",
    question: "盒子裡有紅積木 6 個、藍積木 4 個、黃積木 5 個。哪一種顏色最多？",
    choices: ["紅色", "藍色", "黃色", "一樣多"],
    answer: "紅色",
    explanation: "6 比 5 和 4 都大，所以紅色最多。",
    difficulty: 1
  },
  {
    id: "shape-008",
    world: "積木分類森林",
    shortLabel: "分",
    skill: "分類統計",
    type: "single-choice",
    question: "圖形卡有圓形 8 張、三角形 8 張、正方形 5 張。哪兩種一樣多？",
    choices: ["圓形和三角形", "圓形和正方形", "三角形和正方形", "三種都一樣"],
    answer: "圓形和三角形",
    explanation: "圓形 8 張，三角形 8 張，所以一樣多。",
    difficulty: 1
  },
  {
    id: "shape-009",
    world: "積木分類森林",
    shortLabel: "分",
    skill: "選分類方式",
    type: "single-choice",
    question: "老師要把玩具分成「交通工具」和「不是交通工具」。哪一個應該放在交通工具？",
    choices: ["小車", "皮球", "積木", "娃娃"],
    answer: "小車",
    explanation: "小車可以用來表示交通工具，其他不是交通工具。",
    difficulty: 1
  },
  {
    id: "shape-010",
    world: "積木分類森林",
    shortLabel: "分",
    skill: "看圖判斷",
    type: "picture-choice",
    visual: "正方體：🧊🧊🧊　圓柱：🥫🥫　球：⚽⚽⚽⚽",
    question: "圖中哪一類最多？",
    choices: ["正方體", "圓柱", "球", "一樣多"],
    answer: "球",
    explanation: "球有 4 個，比正方體 3 個、圓柱 2 個都多。",
    difficulty: 1
  },

  {
    id: "share-001",
    world: "公平野餐桌",
    shortLabel: "配",
    skill: "平均分配",
    type: "single-choice",
    question: "12 顆小番茄平均分給 4 人，每人可以分到幾顆？",
    choices: ["2顆", "3顆", "4顆", "8顆"],
    answer: "3顆",
    explanation: "12÷4＝3，所以每人 3 顆。",
    difficulty: 1
  },
  {
    id: "share-002",
    world: "公平野餐桌",
    shortLabel: "配",
    skill: "分裝",
    type: "single-choice",
    question: "18 塊餅乾，每袋裝 3 塊，可以裝成幾袋？",
    choices: ["3袋", "5袋", "6袋", "9袋"],
    answer: "6袋",
    explanation: "18÷3＝6，可以裝成 6 袋。",
    difficulty: 1
  },
  {
    id: "share-003",
    world: "公平野餐桌",
    shortLabel: "配",
    skill: "公平判斷",
    type: "true-false",
    question: "把 10 顆糖分給 2 人，一人 4 顆、一人 6 顆，這樣是平均分配。",
    choices: ["是", "不是"],
    answer: "不是",
    explanation: "平均分配要每人一樣多，4 顆和 6 顆不一樣多。",
    difficulty: 1
  },
  {
    id: "share-004",
    world: "公平野餐桌",
    shortLabel: "配",
    skill: "選正確算式",
    type: "formula-choice",
    question: "24 個飯糰，每盒裝 4 個。要算可以裝幾盒，應該選哪個算式？",
    choices: ["24＋4", "24－4", "24×4", "24÷4"],
    answer: "24÷4",
    explanation: "每盒裝 4 個，就是看 24 裡面有幾個 4，所以用除法。",
    difficulty: 1
  },
  {
    id: "share-005",
    world: "公平野餐桌",
    shortLabel: "配",
    skill: "有剩下",
    type: "single-choice",
    question: "17 顆葡萄平均分給 4 人，每人先分 4 顆，還剩幾顆？",
    choices: ["1顆", "2顆", "3顆", "4顆"],
    answer: "1顆",
    explanation: "4 人每人 4 顆，一共 4×4＝16 顆，17－16＝1 顆。",
    difficulty: 2
  },
  {
    id: "share-006",
    world: "公平野餐桌",
    shortLabel: "配",
    skill: "平均分配",
    type: "single-choice",
    question: "20 根吸管平均放進 5 杯，每杯放幾根？",
    choices: ["4根", "5根", "10根", "15根"],
    answer: "4根",
    explanation: "20÷5＝4，每杯放 4 根。",
    difficulty: 1
  },
  {
    id: "share-007",
    world: "公平野餐桌",
    shortLabel: "配",
    skill: "看圖判斷",
    type: "picture-choice",
    visual: "🥪🥪🥪🥪🥪🥪　分給 3 人",
    question: "6 個三明治平均分給 3 人，每人幾個？",
    choices: ["2個", "3個", "6個", "9個"],
    answer: "2個",
    explanation: "6÷3＝2，所以每人 2 個。",
    difficulty: 1
  },
  {
    id: "share-008",
    world: "公平野餐桌",
    shortLabel: "配",
    skill: "分裝袋數",
    type: "single-choice",
    question: "30 顆丸子，每 5 顆串一串，可以串成幾串？",
    choices: ["5串", "6串", "25串", "35串"],
    answer: "6串",
    explanation: "30÷5＝6，可以串成 6 串。",
    difficulty: 1
  },
  {
    id: "share-009",
    world: "公平野餐桌",
    shortLabel: "配",
    skill: "除法意義",
    type: "single-choice",
    question: "28 張貼紙平均分給 7 人，每人幾張？",
    choices: ["3張", "4張", "7張", "21張"],
    answer: "4張",
    explanation: "28÷7＝4，所以每人 4 張。",
    difficulty: 1
  },
  {
    id: "share-010",
    world: "公平野餐桌",
    shortLabel: "配",
    skill: "公平分配",
    type: "single-choice",
    question: "哪一種分法是平均分配？",
    choices: ["15 顆分給 3 人，每人 5 顆", "12 顆分給 3 人，分成 3、4、5 顆", "8 顆分給 2 人，分成 3、5 顆", "9 顆分給 3 人，分成 2、3、4 顆"],
    answer: "15 顆分給 3 人，每人 5 顆",
    explanation: "每人一樣多才是平均分配。",
    difficulty: 1
  },

  {
    id: "fraction-001",
    world: "分數蛋糕湖",
    shortLabel: "半",
    skill: "一半",
    type: "single-choice",
    question: "把一個圓蛋糕平分成 2 份，每一份是這個蛋糕的多少？",
    choices: ["一半", "一整個", "三分之一", "四分之一"],
    answer: "一半",
    explanation: "平分成 2 份，每份就是一半，也可以說二分之一。",
    difficulty: 1
  },
  {
    id: "fraction-002",
    world: "分數蛋糕湖",
    shortLabel: "半",
    skill: "幾分之一",
    type: "single-choice",
    question: "把一條巧克力平分成 4 份，其中 1 份是幾分之一？",
    choices: ["二分之一", "三分之一", "四分之一", "四分之四"],
    answer: "四分之一",
    explanation: "平分成 4 份，拿其中 1 份，就是四分之一。",
    difficulty: 1
  },
  {
    id: "fraction-003",
    world: "分數蛋糕湖",
    shortLabel: "半",
    skill: "是否平分",
    type: "true-false",
    question: "一個披薩切成大小不一樣的 3 片，也可以說每片都是三分之一。",
    choices: ["是", "不是"],
    answer: "不是",
    explanation: "分數要先平分，大小不一樣就不能說每片都是三分之一。",
    difficulty: 1
  },
  {
    id: "fraction-004",
    world: "分數蛋糕湖",
    shortLabel: "半",
    skill: "簡單比較",
    type: "single-choice",
    question: "同樣大的蛋糕，二分之一和四分之一，哪一個比較大？",
    choices: ["二分之一", "四分之一", "一樣大", "不能比較"],
    answer: "二分之一",
    explanation: "同樣大的蛋糕，分成 2 份的每份比分成 4 份的每份大。",
    difficulty: 2
  },
  {
    id: "fraction-005",
    world: "分數蛋糕湖",
    shortLabel: "半",
    skill: "看圖判斷",
    type: "picture-choice",
    visual: "⬛⬜　代表一個長方形平分成 2 份，塗了 1 份",
    question: "圖中塗色的部分是全部的多少？",
    choices: ["二分之一", "三分之一", "四分之一", "一整個"],
    answer: "二分之一",
    explanation: "平分成 2 份，塗了 1 份，就是二分之一。",
    difficulty: 1
  },
  {
    id: "fraction-006",
    world: "分數蛋糕湖",
    shortLabel: "半",
    skill: "幾分之一",
    type: "single-choice",
    question: "一張紙平分成 3 份，亮亮拿了其中 1 份，他拿了這張紙的多少？",
    choices: ["二分之一", "三分之一", "三分之二", "一整張"],
    answer: "三分之一",
    explanation: "平分成 3 份，拿 1 份，是三分之一。",
    difficulty: 1
  },
  {
    id: "fraction-007",
    world: "分數蛋糕湖",
    shortLabel: "半",
    skill: "平分概念",
    type: "single-choice",
    question: "想把一個蘋果分成二分之一，應該怎麼分？",
    choices: ["切成 2 份，大小一樣", "切成 2 份，一大一小", "切成 3 份", "不用切"],
    answer: "切成 2 份，大小一樣",
    explanation: "二分之一表示平分成 2 份，每份大小一樣。",
    difficulty: 1
  },
  {
    id: "fraction-008",
    world: "分數蛋糕湖",
    shortLabel: "半",
    skill: "簡單比較",
    type: "single-choice",
    question: "同樣大的餅乾，三分之一和四分之一，哪一份比較大？",
    choices: ["三分之一", "四分之一", "一樣大", "都不是"],
    answer: "三分之一",
    explanation: "同樣大的餅乾，分成 3 份的每份比分成 4 份的每份大。",
    difficulty: 2
  },
  {
    id: "fraction-009",
    world: "分數蛋糕湖",
    shortLabel: "半",
    skill: "是非判斷",
    type: "true-false",
    question: "同樣大的長條紙，平分成越多份，每一份會越小。",
    choices: ["是", "不是"],
    answer: "是",
    explanation: "同樣大的東西，平分份數越多，每一份就越小。",
    difficulty: 2
  },
  {
    id: "fraction-010",
    world: "分數蛋糕湖",
    shortLabel: "半",
    skill: "看圖判斷",
    type: "picture-choice",
    visual: "⬛⬜⬜⬜　代表平分成 4 份，塗了 1 份",
    question: "圖中塗色的部分是全部的多少？",
    choices: ["二分之一", "三分之一", "四分之一", "四分之二"],
    answer: "四分之一",
    explanation: "平分成 4 份，塗了 1 份，就是四分之一。",
    difficulty: 1
  },

  {
    id: "final-001",
    world: "期末星光城",
    shortLabel: "勇",
    skill: "兩步驟應用",
    type: "single-choice",
    question: "星光城有 4 排燈，每排 6 盞，壞了 3 盞，還亮著幾盞？",
    choices: ["21盞", "24盞", "27盞", "13盞"],
    answer: "21盞",
    explanation: "先算 4×6＝24，再算 24－3＝21。",
    difficulty: 2
  },
  {
    id: "final-002",
    world: "期末星光城",
    shortLabel: "勇",
    skill: "長度換算",
    type: "single-choice",
    question: "城門高 2 公尺 10 公分，是幾公分？",
    choices: ["210公分", "201公分", "120公分", "21公分"],
    answer: "210公分",
    explanation: "2 公尺是 200 公分，200＋10＝210 公分。",
    difficulty: 1
  },
  {
    id: "final-003",
    world: "期末星光城",
    shortLabel: "勇",
    skill: "平均分配",
    type: "single-choice",
    question: "30 顆星星珠平均串成 5 條手鍊，每條有幾顆？",
    choices: ["5顆", "6顆", "25顆", "35顆"],
    answer: "6顆",
    explanation: "30÷5＝6，每條 6 顆。",
    difficulty: 1
  },
  {
    id: "final-004",
    world: "期末星光城",
    shortLabel: "勇",
    skill: "立體形體",
    type: "single-choice",
    question: "星光城的禮物盒最像長方體，下面哪一個也最像長方體？",
    choices: ["鞋盒", "足球", "飲料罐", "硬幣"],
    answer: "鞋盒",
    explanation: "鞋盒長長方方，有平平的面，最像長方體。",
    difficulty: 1
  },
  {
    id: "final-005",
    world: "期末星光城",
    shortLabel: "勇",
    skill: "分數比較",
    type: "single-choice",
    question: "同樣大的星星餅，二分之一和三分之一，哪一份比較大？",
    choices: ["二分之一", "三分之一", "一樣大", "不能比較"],
    answer: "二分之一",
    explanation: "同樣大的餅，平分成 2 份的每份比平分成 3 份的每份大。",
    difficulty: 2
  },
  {
    id: "final-006",
    world: "期末星光城",
    shortLabel: "勇",
    skill: "選正確算式",
    type: "formula-choice",
    question: "20 張票先用掉 8 張，剩下的平均分給 4 組。每組幾張？哪個算式正確？",
    choices: ["20－8÷4", "(20－8)÷4", "20＋8÷4", "20÷4－8"],
    answer: "(20－8)÷4",
    explanation: "要先算剩下幾張票，再平均分給 4 組。",
    difficulty: 2
  },
  {
    id: "final-007",
    world: "期末星光城",
    shortLabel: "勇",
    skill: "看圖判斷",
    type: "picture-choice",
    visual: "燈籠：🏮🏮🏮🏮　星球：⚽⚽　積木：🧊🧊🧊",
    question: "圖中哪一類最多？",
    choices: ["燈籠", "星球", "積木", "一樣多"],
    answer: "燈籠",
    explanation: "燈籠有 4 個，比星球 2 個、積木 3 個多。",
    difficulty: 1
  },
  {
    id: "final-008",
    world: "期末星光城",
    shortLabel: "勇",
    skill: "長度差",
    type: "single-choice",
    question: "星光橋長 180 公分，彩帶長 2 公尺。彩帶比星光橋長幾公分？",
    choices: ["20公分", "80公分", "180公分", "380公分"],
    answer: "20公分",
    explanation: "2 公尺是 200 公分，200－180＝20 公分。",
    difficulty: 2
  },
  {
    id: "final-009",
    world: "期末星光城",
    shortLabel: "勇",
    skill: "公平判斷",
    type: "true-false",
    question: "16 顆星星糖平均分給 4 人，每人 4 顆，這是平均分配。",
    choices: ["是", "不是"],
    answer: "是",
    explanation: "每人都得到 4 顆，一樣多，所以是平均分配。",
    difficulty: 1
  },
  {
    id: "final-010",
    world: "期末星光城",
    shortLabel: "勇",
    skill: "綜合挑戰",
    type: "single-choice",
    question: "完成星光城任務後，18 顆寶石平均放進 3 個寶箱，每箱再加 2 顆，每箱有幾顆？",
    choices: ["6顆", "8顆", "12顆", "20顆"],
    answer: "8顆",
    explanation: "先算 18÷3＝6，再算每箱 6＋2＝8。",
    difficulty: 2
  }
];
